<?php

namespace MISA\MprojectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssignationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignationRepository extends EntityRepository
{
}
