<?php

namespace MISA\MprojectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function findWithClient(){
		$qb = $this->createQueryBuilder('p')
					->join('p.client', 'c')
					->addSelect('c')
		;

		return $qb->getQuery()->getResult();
	}

	public function findToAssign(){
		$qb = $this->createQueryBuilder('p')
					->join('p.client', 'c')
					->addSelect('c')
		;

		$qb->where($qb->expr()->isNull('p.assignation'));

		return $qb->getQuery()->getResult();
	}
}
